CONFIG = {
    'friends_audio': {
        'min_segment_dur': 1 * 1000,
        'max_segment_dur': 10 * 1000,
        'min_silence_len': 500,
        'silence_thresh': -20,
    },
    'drunk_woman': {
        'min_segment_dur': 1 * 1000,
        'max_segment_dur': 1 * 1000,
        'min_silence_len': 100,
        'silence_thresh': -40,
    },
    'Переговоры_диспетчеров_с_пьяным_машинистом_в_московском_метро_на': {
        'min_segment_dur': 1 * 1000,
        'max_segment_dur': 10 * 1000,
        'min_silence_len': 100,
        'silence_thresh': -50,
    },
    'Пьяные_разговоры': {
        'min_segment_dur': 1 * 1000,
        'max_segment_dur': 10 * 1000,
        'min_silence_len': 100,
        'silence_thresh': -55,
    },
    'Разговор_пьяного_мужа': {
        'min_segment_dur': 1 * 1000,
        'max_segment_dur': 10 * 1000,
        'min_silence_len': 200,
        'silence_thresh': -40,
    },
    'Умный_домофон_не_пускает_домой_пьяного': {
        'min_segment_dur': 1 * 1000,
        'max_segment_dur': 10 * 1000,
        'min_silence_len': 200,
        'silence_thresh': -30,
    },
    'russian_memes': {
        'min_segment_dur': 1 * 1000,
        'max_segment_dur': 25 * 1000,
        'min_silence_len': 200,
        'silence_thresh': -40,
    },
    'alco_videos_1': {
        'min_segment_dur': 1 * 1000,
        'max_segment_dur': 10 * 1000,
        'min_silence_len': 200,
        'silence_thresh': -40,
    },
    'alco_videos_2': {
        'min_segment_dur': 0.5 * 1000,
        'max_segment_dur': 10 * 1000,
        'min_silence_len': 100,
        'silence_thresh': -35,
    },
    'alco_videos_3': {
        'min_segment_dur': 1 * 1000,
        'max_segment_dur': 10 * 1000,
        'min_silence_len': 100,
        'silence_thresh': -35,
    },
    'alco_videos_4': {
        'min_segment_dur': 1 * 1000,
        'max_segment_dur': 10 * 1000,
        'min_silence_len': 100,
        'silence_thresh': -40,
    },
    'Пьяные_сцены_из_советских_комедий': {
        'min_segment_dur': 1 * 1000,
        'max_segment_dur': 10 * 1000,
        'min_silence_len': 100,
        'silence_thresh': -45,
    },
    'yes_man': {
        'min_segment_dur': 1 * 1000,
        'max_segment_dur': 10 * 1000,
        'min_silence_len': 100,
        'silence_thresh': -30,
    },
    'купе_номер_6': {
        'min_segment_dur': 1 * 1000,
        'max_segment_dur': 10 * 1000,
        'min_silence_len': 100,
        'silence_thresh': -20,
    },
    'славик_и_димон': {
        'min_segment_dur': 1 * 1000,
        'max_segment_dur': 10 * 1000,
        'min_silence_len': 100,
        'silence_thresh': -40,
    },
    'Приколы_с_алкашами_1': {
        'min_segment_dur': 1 * 1000,
        'max_segment_dur': 10 * 1000,
        'min_silence_len': 100,
        'silence_thresh': -40,
    },
    'Приколы_с_алкашами_2': {
        'min_segment_dur': 1 * 1000,
        'max_segment_dur': 10 * 1000,
        'min_silence_len': 100,
        'silence_thresh': -50,
    },
    'Приколы_с_алкашами_3': {
        'min_segment_dur': 1 * 1000,
        'max_segment_dur': 10 * 1000,
        'min_silence_len': 100,
        'silence_thresh': -30,
    },
    'Приколы_с_алкашами_4': {
        'min_segment_dur': 1 * 1000,
        'max_segment_dur': 10 * 1000,
        'min_silence_len': 500,
        'silence_thresh': -45,
    },
    'Приколы_с_алкашами_5': {
        'min_segment_dur': 1 * 1000,
        'max_segment_dur': 10 * 1000,
        'min_silence_len': 500,
        'silence_thresh': -35,
    },
    'Приколы_с_алкашами_6': {
        'min_segment_dur': 1 * 1000,
        'max_segment_dur': 10 * 1000,
        'min_silence_len': 500,
        'silence_thresh': -20,
    },
    'Приколы_с_алкашами_7': {
        'min_segment_dur': 1 * 1000,
        'max_segment_dur': 10 * 1000,
        'min_silence_len': 500,
        'silence_thresh': -27,
    },
    'tost': {
        'min_segment_dur': 1 * 1000,
        'max_segment_dur': 10 * 1000,
        'min_silence_len': 1000,
        'silence_thresh': -35,
    },
    'Пьяный_за_столом': {
        'min_segment_dur': 1 * 1000,
        'max_segment_dur': 10 * 1000,
        'min_silence_len': 1000,
        'silence_thresh': -20,
    },
    'alco_videos_5': {
        'min_segment_dur': 1 * 1000,
        'max_segment_dur': 10 * 1000,
        'min_silence_len': 300,
        'silence_thresh': -25,
    },
    'alco_videos_6': {
        'min_segment_dur': 1 * 1000,
        'max_segment_dur': 10 * 1000,
        'min_silence_len': 300,
        'silence_thresh': -30,
    },
    'Неадекватный_машинист': {
        'min_segment_dur': 1 * 1000,
        'max_segment_dur': 10 * 1000,
        'min_silence_len': 300,
        'silence_thresh': -40,
    },
    'Сумасшедшие_бабки_1': {
        'min_segment_dur': 1 * 1000,
        'max_segment_dur': 10 * 1000,
        'min_silence_len': 300,
        'silence_thresh': -35,
    },
    'Сумасшедшие_бабки_2': {
        'min_segment_dur': 1 * 1000,
        'max_segment_dur': 10 * 1000,
        'min_silence_len': 300,
        'silence_thresh': -40,
    },
    'Сумасшедшие_бабки_3': {
        'min_segment_dur': 1 * 1000,
        'max_segment_dur': 10 * 1000,
        'min_silence_len': 600,
        'silence_thresh': -35,
    },
    'Муж_вернулся_пьяный_домой_6_кадров': {
        'min_segment_dur': 1 * 1000,
        'max_segment_dur': 10 * 1000,
        'min_silence_len': 300,
        'silence_thresh': -35,
    },
    'пьяный_сын_возвращается_домой': {
        'min_segment_dur': 1 * 1000,
        'max_segment_dur': 10 * 1000,
        'min_silence_len': 300,
        'silence_thresh': -40,
    },
    'Пьяный_отец_возвращается_домой': {
        'min_segment_dur': 1 * 1000,
        'max_segment_dur': 10 * 1000,
        'min_silence_len': 1000,
        'silence_thresh': -30,
    },
    'Пьяный_сын_пришел_домой': {
        'min_segment_dur': 1 * 1000,
        'max_segment_dur': 10 * 1000,
        'min_silence_len': 500,
        'silence_thresh': -40,
    },
    'Пьяный_сторож_на_стройке': {
        'min_segment_dur': 1 * 1000,
        'max_segment_dur': 10 * 1000,
        'min_silence_len': 200,
        'silence_thresh': -28,
    },
    'Пьяный_быдлан_в_поезде': {
        'min_segment_dur': 1 * 1000,
        'max_segment_dur': 10 * 1000,
        'min_silence_len': 200,
        'silence_thresh': -30,
    },
    'Пьяный_и_рыдающий_маменькин_сынок_напал_на_полицейского_в_поезде': {
        'min_segment_dur': 1 * 1000,
        'max_segment_dur': 10 * 1000,
        'min_silence_len': 200,
        'silence_thresh': -38,
    },
    'С_поезда_сняли_пьяного_дебошира': {
        'min_segment_dur': 1 * 1000,
        'max_segment_dur': 15 * 1000,
        'min_silence_len': 600,  # 500
        'silence_thresh': -15,
    },
    'Пьяная_хулиганка_в_поезде': {
        'min_segment_dur': 1 * 1000,
        'max_segment_dur': 15 * 1000,
        'min_silence_len': 500,
        'silence_thresh': -18,  # -25
    },
    'Трёх_пьяных_дебоширов_сняли_с_поезда_в_Сургуте': {
        'min_segment_dur': 1 * 1000,
        'max_segment_dur': 15 * 1000,
        'min_silence_len': 500,
        'silence_thresh': -30,
    },
    'Пьяный_дебош_в_Апатитской_больнице': {
        'min_segment_dur': 1 * 1000,
        'max_segment_dur': 15 * 1000,
        'min_silence_len': 500,
        'silence_thresh': -30,
    },
    'пьяные_устроили_дебош_в_автобусе_Мурманска': {
        'min_segment_dur': 1 * 1000,
        'max_segment_dur': 15 * 1000,
        'min_silence_len': 500,
        'silence_thresh': -20,  # -30
    },
    'Пьяный_в_ресторане_6_кадров': {
        'min_segment_dur': 1 * 1000,
        'max_segment_dur': 15 * 1000,
        'min_silence_len': 500,
        'silence_thresh': -32,  # -30
    },
    'Пьяный_в_поезде': {
        'min_segment_dur': 1 * 1000,
        'max_segment_dur': 15 * 1000,
        'min_silence_len': 500,
        'silence_thresh': -30,  # -40
    },
    'Drunk_in_train_Rostov': {
        'min_segment_dur': 1 * 1000,
        'max_segment_dur': 15 * 1000,
        'min_silence_len': 500,
        'silence_thresh': -47,
    },
    'Drunk_trainer_in_train': {
        'min_segment_dur': 1 * 1000,
        'max_segment_dur': 15 * 1000,
        'min_silence_len': 500,
        'silence_thresh': -27,
    },
    'Drunk_lady_on_lake_shore': {
        'min_segment_dur': 1 * 1000,
        'max_segment_dur': 15 * 1000,
        'min_silence_len': 500,
        'silence_thresh': -30,
    },
    '6_frames_drunk_in_pharmacy': {
        'min_segment_dur': 1 * 1000,
        'max_segment_dur': 15 * 1000,
        'min_silence_len': 500,
        'silence_thresh': -20,
    },
    'invented_vodka_again': {
        'min_segment_dur': 1 * 1000,
        'max_segment_dur': 15 * 1000,
        'min_silence_len': 500,
        'silence_thresh': -30,
    },
    'drunk_mother_with_child': {
        'min_segment_dur': 1 * 1000,
        'max_segment_dur': 15 * 1000,
        'min_silence_len': 500,
        'silence_thresh': -45,  # -25
    },
    'drunk_neighbor': {
        'min_segment_dur': 1 * 1000,
        'max_segment_dur': 15 * 1000,
        'min_silence_len': 300,
        'silence_thresh': -35,  # -30
    },
    'drunk_builders': {
        'min_segment_dur': 1 * 1000,
        'max_segment_dur': 15 * 1000,
        'min_silence_len': 300,
        'silence_thresh': -30,
    },
    'drunk_wife_of_policeman': {
        'min_segment_dur': 1 * 1000,
        'max_segment_dur': 15 * 1000,
        'min_silence_len': 300,  # 500
        'silence_thresh': -35,
    },
    'drunk_patient': {
        'min_segment_dur': 1 * 1000,
        'max_segment_dur': 15 * 1000,
        'min_silence_len': 300,
        'silence_thresh': -30,
    },
}
