CONFIG = {
    'friends_audio': {
        'min_segment_dur': 1 * 1000,
        'max_segment_dur': 10 * 1000,
        'min_silence_len': 500,
        'silence_thresh': -20,
    },
    'drunk_woman': {
        'min_segment_dur': 1 * 1000,
        'max_segment_dur': 1 * 1000,
        'min_silence_len': 100,
        'silence_thresh': -40,
    },
    'Переговоры_диспетчеров_с_пьяным_машинистом_в_московском_метро_на': {
        'min_segment_dur': 1 * 1000,
        'max_segment_dur': 10 * 1000,
        'min_silence_len': 100,
        'silence_thresh': -50,
    },
    'Пьяные_разговоры': {
        'min_segment_dur': 1 * 1000,
        'max_segment_dur': 10 * 1000,
        'min_silence_len': 100,
        'silence_thresh': -55,
    },
    'Разговор_пьяного_мужа': {
        'min_segment_dur': 1 * 1000,
        'max_segment_dur': 10 * 1000,
        'min_silence_len': 200,
        'silence_thresh': -40,
    },
    'Умный_домофон_не_пускает_домой_пьяного': {
        'min_segment_dur': 1 * 1000,
        'max_segment_dur': 10 * 1000,
        'min_silence_len': 200,
        'silence_thresh': -30,
    },
    'russian_memes': {
        'min_segment_dur': 1 * 1000,
        'max_segment_dur': 25 * 1000,
        'min_silence_len': 200,
        'silence_thresh': -40,
    },
    'alco_videos_1': {
        'min_segment_dur': 1 * 1000,
        'max_segment_dur': 10 * 1000,
        'min_silence_len': 200,
        'silence_thresh': -40,
    },
    'alco_videos_2': {
        'min_segment_dur': 0.5 * 1000,
        'max_segment_dur': 10 * 1000,
        'min_silence_len': 100,
        'silence_thresh': -35,
    },
    'alco_videos_3': {
        'min_segment_dur': 1 * 1000,
        'max_segment_dur': 10 * 1000,
        'min_silence_len': 100,
        'silence_thresh': -35,
    },
    'alco_videos_4': {
        'min_segment_dur': 1 * 1000,
        'max_segment_dur': 10 * 1000,
        'min_silence_len': 100,
        'silence_thresh': -40,
    },
    'Пьяные_сцены_из_советских_комедий': {
        'min_segment_dur': 1 * 1000,
        'max_segment_dur': 10 * 1000,
        'min_silence_len': 100,
        'silence_thresh': -45,
    },
    'yes_man': {
        'min_segment_dur': 1 * 1000,
        'max_segment_dur': 10 * 1000,
        'min_silence_len': 100,
        'silence_thresh': -30,
    },
    'купе_номер_6': {
        'min_segment_dur': 1 * 1000,
        'max_segment_dur': 10 * 1000,
        'min_silence_len': 100,
        'silence_thresh': -20,
    },
    'славик_и_димон': {
        'min_segment_dur': 1 * 1000,
        'max_segment_dur': 10 * 1000,
        'min_silence_len': 100,
        'silence_thresh': -40,
    },
    'Приколы_с_алкашами_1': {
        'min_segment_dur': 1 * 1000,
        'max_segment_dur': 10 * 1000,
        'min_silence_len': 100,
        'silence_thresh': -40,
    },
    'Приколы_с_алкашами_2': {
        'min_segment_dur': 1 * 1000,
        'max_segment_dur': 10 * 1000,
        'min_silence_len': 100,
        'silence_thresh': -50,
    },
    'Приколы_с_алкашами_3': {
        'min_segment_dur': 1 * 1000,
        'max_segment_dur': 10 * 1000,
        'min_silence_len': 100,
        'silence_thresh': -30,
    },
    'Приколы_с_алкашами_4': {
        'min_segment_dur': 1 * 1000,
        'max_segment_dur': 10 * 1000,
        'min_silence_len': 500,
        'silence_thresh': -45,
    },
    'Приколы_с_алкашами_5': {
        'min_segment_dur': 1 * 1000,
        'max_segment_dur': 10 * 1000,
        'min_silence_len': 500,
        'silence_thresh': -35,
    },
    'Приколы_с_алкашами_6': {
        'min_segment_dur': 1 * 1000,
        'max_segment_dur': 10 * 1000,
        'min_silence_len': 500,
        'silence_thresh': -20,
    },
    'Приколы_с_алкашами_7': {
        'min_segment_dur': 1 * 1000,
        'max_segment_dur': 10 * 1000,
        'min_silence_len': 500,
        'silence_thresh': -27,
    },
    'tost': {
        'min_segment_dur': 1 * 1000,
        'max_segment_dur': 10 * 1000,
        'min_silence_len': 1000,
        'silence_thresh': -35,
    },
    'Пьяный_за_столом': {
        'min_segment_dur': 1 * 1000,
        'max_segment_dur': 10 * 1000,
        'min_silence_len': 1000,
        'silence_thresh': -20,
    },
    'alco_videos_5': {
        'min_segment_dur': 1 * 1000,
        'max_segment_dur': 10 * 1000,
        'min_silence_len': 300,
        'silence_thresh': -25,
    },
    'alco_videos_6': {
        'min_segment_dur': 1 * 1000,
        'max_segment_dur': 10 * 1000,
        'min_silence_len': 300,
        'silence_thresh': -30,
    },
    'Неадекватный_машинист': {
        'min_segment_dur': 1 * 1000,
        'max_segment_dur': 10 * 1000,
        'min_silence_len': 300,
        'silence_thresh': -40,
    },
}
